version: "3.2"

services:
  bitcoind:
    image: "samouraiwallet/dojo-bitcoind:${DOJO_BITCOIND_VERSION_TAG}"
    container_name: bitcoind
    build:
      context: ./bitcoin
      args:
        BITCOIND_LINUX_UID: ${BITCOIND_LINUX_UID}
        BITCOIND_LINUX_GID: ${BITCOIND_LINUX_GID}
        TOR_LINUX_GID: ${TOR_LINUX_GID}
    env_file:
      - ./.env
      - ./conf/docker-common.conf
      - ./conf/docker-bitcoind.conf
    restart: always
    command: "/wait-for-it.sh tor:9050 --timeout=720 --strict -- /restart.sh"
    expose:
      - "8333"
      - "28256"
      - "9501"
      - "9502"
    volumes:
      - data-bitcoind:/home/bitcoin/.bitcoin
      - data-tor:/var/lib/tor
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - db
      - tor
    networks:
      dojonet:
        ipv4_address: ${NET_DOJO_BITCOIND_IPV4}

  node:
    depends_on:
      - bitcoind

volumes:
  data-bitcoind:
