version: "3.2"

services:
  fulcrum:
    image: "samouraiwallet/dojo-fulcrum:${DOJO_FULCRUM_VERSION_TAG}"
    container_name: fulcrum
    build:
      context: ./fulcrum
      args:
        FULCRUM_LINUX_UID: ${FULCRUM_LINUX_UID}
        FULCRUM_LINUX_GID: ${FULCRUM_LINUX_GID}
    env_file:
      - ./.env
      - ./conf/docker-common.conf
      - ./conf/docker-bitcoind.conf
      - ./conf/docker-indexer.conf
    restart: on-failure
    command: /restart.sh
    expose:
      - "50001"
    volumes:
      - data-fulcrum:/home/fulcrum
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    stop_grace_period: 1m
    depends_on:
      - tor
      - node
    networks:
      dojonet:
        ipv4_address: ${NET_DOJO_INDEXER_IPV4}

volumes:
  data-fulcrum:
