version: "3.2"

services:
  db:
    image: "samouraiwallet/dojo-db:${DOJO_DB_VERSION_TAG}"
    container_name: db
    build:
      context: ./../..
      dockerfile: ./docker/my-dojo/mysql/Dockerfile
    env_file:
      - ./.env
      - ./conf/docker-mysql.conf
    restart: always
    expose:
      - "3306"
    volumes:
      - data-mysql:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      dojonet:
        ipv4_address: ${NET_DOJO_MYSQL_IPV4}

  node:
    image: "samouraiwallet/dojo-nodejs:${DOJO_NODEJS_VERSION_TAG}"
    container_name: nodejs
    build:
      context: ./../..
      dockerfile: ./docker/my-dojo/node/Dockerfile
      args:
        TOR_LINUX_GID: ${TOR_LINUX_GID}
    env_file:
      - ./.env
      - ./conf/docker-common.conf
      - ./conf/docker-mysql.conf
      - ./conf/docker-bitcoind.conf
      - ./conf/docker-explorer.conf
      - ./conf/docker-indexer.conf
      - ./conf/docker-node.conf
      - ./conf/docker-tor.conf
    restart: always
    command: "/home/node/app/wait-for-it.sh db:3306 --timeout=720 --strict -- /home/node/app/restart.sh"
    expose:
      - "8080"
      - "8081"
      - "8082"
    volumes:
      - data-tor:/var/lib/tor
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - db
    networks:
      dojonet:
        ipv4_address: ${NET_DOJO_NODE_IPV4}

  nginx:
    image: "samouraiwallet/dojo-nginx:${DOJO_NGINX_VERSION_TAG}"
    container_name: nginx
    build:
      context: ./nginx
    env_file:
      - ./.env
      - ./conf/docker-common.conf
    restart: always
    command: "/wait-for node:8080 --timeout=720 -- nginx"
    expose:
      - "80"
      - "9080"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - node
    networks:
      whirlnet:
        ipv4_address: ${NET_WHIRL_NGINX_IPV4}
      dmznet:
        ipv4_address: ${NET_DMZ_NGINX_IPV4}
      dojonet:
        ipv4_address: ${NET_DOJO_NGINX_IPV4}

  tor:
    image: "samouraiwallet/dojo-tor:${DOJO_TOR_VERSION_TAG}"
    container_name: tor
    build:
      context: ./tor
      args:
        TOR_LINUX_UID: ${TOR_LINUX_UID}
        TOR_LINUX_GID: ${TOR_LINUX_GID}
    env_file:
      - ./.env
      - ./conf/docker-bitcoind.conf
      - ./conf/docker-explorer.conf
      - ./conf/docker-whirlpool.conf
      - ./conf/docker-indexer.conf
      - ./conf/docker-tor.conf
    restart: always
    command: /restart.sh
    volumes:
      - data-tor:/var/lib/tor
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      dmznet:
        ipv4_address: ${NET_DMZ_TOR_IPV4}
      dojonet:
        ipv4_address: ${NET_DOJO_TOR_IPV4}

networks:
  dojonet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  dmznet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
  whirlnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16

volumes:
  data-mysql:
  data-tor:
